name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t koti21/agentic_ai:latest

    - name: Push Docker image to Docker Hub
      run: docker push koti21/agentic_ai:latest

  Deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Pull the Docker Image
        run: docker pull koti21/agentic_ai:latest
        
      - name: Delete Old Container
        run: |
          if [ "$(docker ps -q -f name=agentic_ai_container)" ]; then
            sudo docker rm -f agentic_ai_container
          fi
          
      - name: Run the Container
        run: docker run -d -p 80:80 --name agentic_ai_container koti21/agentic_ai
